name: voila-hello-world-example
channels:
  - conda-forge
dependencies:
  - ipywidgets=7.5
  - voila=0.1.5
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask


